/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package otio.tryy;

import io.opentimeline.opentime.RationalTime;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        RationalTime rationalTime = new RationalTime();
        System.out.println(rationalTime.toString());
    }
}
